#!/usr/bin/env python

from time import sleep, time
from traceback import print_exc

from requests import get

from hosted import CONFIG, DEVICE, log

CONFIG.restart_on_update()


def main():
    sleep(2)

    URL = CONFIG["url"].rstrip("/")
    TOKEN = CONFIG["api_token"]
    ENTITY = CONFIG["entity_id"]
    COMP = CONFIG["comparison"]
    TARGET = CONFIG["target"]
    SLEEP = CONFIG["request_interval"]

    if not URL:
        # default config
        sleep(86400)

    last_change = 0
    old_state = None
    new_state = None

    while True:
        try:
            url = URL + "/api/states/" + ENTITY
            log("getting " + url, "HASS")

            r = get(
                url,
                headers={
                    "Authorization": "Bearer " + TOKEN,
                    "Content-Type": "application/json",
                },
            )
            log(str(r.status_code), "HASS")
            log(r.text, "HASS")

            r.raise_for_status()
            result = r.json()

            if "state" not in result:
                # oops?
                log("ERR: no state, switching on", "HASS")

                new_state = True
            else:
                if TARGET.isdigit():
                    TARGET = int(TARGET)
                    state = int(result["state"])
                else:
                    state = result["state"]

                if COMP == "lt":
                    target_state = bool(state < TARGET)
                elif COMP == "le":
                    target_state = bool(state <= TARGET)
                elif COMP == "gt":
                    target_state = bool(state > TARGET)
                elif COMP == "ge":
                    target_state = bool(state >= TARGET)
                elif COMP == "eq":
                    target_state = bool(state == TARGET)
                else:
                    raise ValueError("invalid comparison")

                log("got state, target is " + str(target_state), "HASS")

                new_state = target_state
        except Exception as e:
            print_exc()

        if old_state != new_state:
            log(
                "state changed, old " + str(old_state) + ", new " + str(new_state),
                "HASS",
            )
            old_state = new_state
            DEVICE.screen(on=new_state)
            last_change = int(time())

        sleep_until = time() + SLEEP + 1
        log("sleeping for a total of " + str(SLEEP) + " seconds", "HASS")
        while int(time()) < sleep_until:
            remaining = sleep_until - time()
            log("sleeping, " + str(remaining) + " seconds remaining", "HASS")

            if last_change < int(time()) - 30:
                log("periodic screen state refresher", "HASS")
                DEVICE.screen(on=old_state)
                last_change = int(time())

            sleep(1)


if __name__ == "__main__":
    main()
